# Generated by Django 6.0.1 on 2026-02-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procon', '0002_submission_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
