# Generated by Django 6.0.1 on 2026-02-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procon', '0003_problem_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
