# Generated by Django 6.0.1 on 2026-02-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procon', '0004_testcase_is_sample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['score', 'created_at']},
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
